# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title                     : 유년시절
title_separator           : "-"
subtitle                  : uniony's blog # site tagline that appears below site title in masthead
email                     : kimuniony@gmail.com
description               : >- # this means to ignore newlines until "baseurl:"
  유년이의 블로그. Uniony's blog
# Write an awesome description for your new site here. You can edit this
# line in _config.yml. It will appear in your document head meta (for
# Google search results) and in your feed.xml site description.
twitter_username          : 
github_username           : unionyy
minimal_mistakes_skin     : "dark" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"
search                    : true # true, false (default)
search_full_content       : true # true, false (default)
# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: KR # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # https://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "유년"
  avatar : "/assets/images/bio-photo.jpg"
  bio    : "bloging..."
  links:
    - label: "Blog"
      icon: "fas fa-fw fa-link"
      url: "https://blog.uniony.me/"
    - label: "unionyy"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/unionyy"
    - label: "yoonyeony"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/yoonyeony/"

footer:
  links:
    - label: "Blog"
      icon: "fas fa-fw fa-link"
      url: "https://blog.uniony.me/"
    - label: "unionyy"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/unionyy"
    - label: "yoonyeony"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/yoonyeony/"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      #classes: wide
      show_date: true
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: false
      related: true
      toc: true
      toc_sticky: true
      toc_label: "목차"
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

repository: unionyy/blog

comments:
  provider: "utterances"
  utterances:
    theme: "github-light" # "github-dark"
    issue_term: "pathname"