# Theme Settings
remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin     : "dark" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

# Site settings
locale                    : "kr-KR"
title                     : "유년시절"
masthead_title            : "유년시절" # overrides the website title displayed in the masthead, use " " for no title
subtitle                  : # site tagline that appears below site title in masthead
name                      : "유년"
title_separator           : "-"
subtitle                  : # site tagline that appears below site title in masthead
email                     : "kyh4323@gmail.com"
description               : >- # this means to ignore newlines until "baseurl:"
  유년이의 블로그. Uniony's blog
# Write an awesome description for your new site here. You can edit this
# line in _config.yml. It will appear in your document head meta (for
# Google search results) and in your feed.xml site description.
url                       : "https://blog.uniony.me"
repository                : "unionyy/blog"
github_username           : "unionyy"

teaser                    : # path of fallback teaser image, e.g. "/assets/images/500x300.png"
logo                      : # path of logo image to display in the masthead, e.g. "/assets/images/88x88.png"
words_per_minute          : 100
comments:
  provider: "utterances"
  utterances:
    theme: "photon-dark" # "github-dark"
    issue_term: "pathname"

search                    : true # true, false (default)
search_full_content       : true # true, false (default)

# Analytics
analytics:
  provider: "google"
  google:
    tracking_id: "G-5VLYJWQNP2"
    anonymize_ip: false # default

# Build settings
markdown: kramdown

# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: KR # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # https://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name    : "유년"
  avatar  : "/assets/images/bio-photo.jpg"
  bio     : "Software Engineer"
  location: "Somewhere, Korea"
  links:
    - label: "Blog"
      icon: "fas fa-fw fa-link"
      url: "https://blog.uniony.me/"
    - label: "unionyy"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/unionyy"
    - label: "yoonyeony"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/yoonyeony/"

footer:
  links:
    - label: "Blog"
      icon: "fas fa-fw fa-link"
      url: "https://blog.uniony.me/"
    - label: "unionyy"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/unionyy"
    - label: "yoonyeony"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/yoonyeony/"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      #classes: wide
      show_date: true
      layout: single
      author_profile: true
      read_time: false
      comments: true
      share: false
      related: true
      toc: true
      toc_sticky: true
      toc_label: "목차"
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

